### ISSUE TITLE
Can't write values for fields with no pre-existing values

### ISSUE THREAD

**Issue by WHTaylor** [WHTaylor/icat-admin#34]
The somewhat vague title means:
 - If an entity table has no entries, it's not possible to create any
 - If none of the entities in a table have an attribute set, it's not possible to set that value for any entities

Both of these have the same root cause; icat-admin doesn't know anything about the fields on the ICAT entity types[^1], it just renders whatever values ICAT returns to it. That means that if ICAT doesn't return any entities, or none of the entities have a particular field populated, icat-admin can't display anything.

The solution to this would be to add the structure of the ICAT schema to icat-admin:
 - Better believe I'm not doing it manually. Don't want it to happen at runtime either, so it can either be done as part of the build step, or by a separate tool that produces something that can be committed to the repo. Scraping https://repo.icatproject.org/site/icat/server/6.0.0/schema.html is a possible answer, is there a better place to get the info?
 - Have to decide what to do about displaying columns that are entirely empty. Probably a toggle in the entity table header.

[^1]: Except special case info for [links to related entities](https://github.com/WHTaylor/icat-admin/blob/58937197ffa70d27dd55656d7cab34ddbc9a3633/src/utils.ts#L17), and the existence of id, modTime/Id, and createTime/Id, for table column sorting)

**Comment by louise-davies** [comment]
Commenting on this because this is an issue that us in DSEG would like resolving as it is quite annoying when setting up a new dev ICAT.

There's no method in the REST API to get the entity info, but there is on the [SOAP API](https://repo.icatproject.org/site/icat/server/6.0.0/soap.html#information)- which if you're thinking on not doing it at runtime (either as a build step or a separate tool) should not be an issue. Python-icat already does this building of the entity map using the SOAP API methods, so perhaps that could be a useful tool to help extract the schema info (https://python-icat.readthedocs.io/en/stable/client.html#icat.client.Client.typemap) or at the very least, it's source code for it's own parsing can act as a guide to using the SOAP API directly: https://github.com/icatproject/python-icat/blob/902c427f1f84f643a685cb1d98039b08c1a8162c/src/icat/entities.py#L229

**Comment by WHTaylor** [comment]
I've added a 'Show empty columns' checkbox to the table view controls which makes it possible to input values for otherwise all null fields :

![image](https://github.com/user-attachments/assets/d6225d19-6e61-4431-9b12-eb2cd6d8b5e1)
---
![image](https://github.com/user-attachments/assets/4d5dd7b8-89f8-4402-bf01-dde2d3196c9f)
---
![image](https://github.com/user-attachments/assets/bfd5844f-e7d7-4afc-adcb-6b95151cc9a1)
